import { ArrowRight, Check, Menu, MessageCircle, X } from 'lucide-react'
import { createRoot } from 'react-dom/client'
import { FormEvent, useEffect, useRef, useState } from 'react'
import './styles.css'
import logo from './assets/orkestia-logo.jpeg'
import hero from './assets/hero-devices.png'
import maestro from './assets/maestro.png'
import legato from './assets/legato.png'
import agro from './assets/agro.png'
import development from './assets/dev-section.png'

const whatsapp = '5519989840708'
const solutions = [
  { title: 'Orkestia Maestro', text: 'Gestão inteligente para operações, manutenção, engenharia e processos.', image: maestro, tag: 'Gestão operacional', features: ['Ordens de serviço e manutenção', 'Indicadores e agenda operacional', 'Histórico completo por ativo'] },
  { title: 'Orkestia Legato', text: 'Tecnologia e organização para a rotina jurídica e seus processos.', image: legato, tag: 'Gestão jurídica', features: ['Controle de processos e prazos', 'Visão clara da carteira', 'Fluxos e documentos centralizados'] },
  { title: 'Orkestia Agro', text: 'Dados, sensores e controle para uma operação rural mais eficiente.', image: agro, tag: 'Tecnologia no campo', features: ['Monitoramento da propriedade', 'Dados de solo e clima', 'Gestão de safras e operações'] }
]
const whatsappUrl = (message: string) => `https://wa.me/${whatsapp}?text=${encodeURIComponent(message)}`

function Reveal({ children, className = '' }: { children: React.ReactNode; className?: string }) { const ref = useRef<HTMLDivElement>(null); useEffect(() => { const element = ref.current; if (!element) return; const observer = new IntersectionObserver(([entry]) => entry.isIntersecting && element.classList.add('is-visible'), { threshold: .12 }); observer.observe(element); return () => observer.disconnect() }, []); return <div ref={ref} className={`reveal ${className}`}>{children}</div> }
function Counter({ value, suffix = '' }: { value: number; suffix?: string }) { const [count, setCount] = useState(0); const ref = useRef<HTMLSpanElement>(null); useEffect(() => { const element = ref.current; if (!element) return; const observer = new IntersectionObserver(([entry]) => { if (!entry.isIntersecting) return; const started = performance.now(); const tick = (time: number) => { const progress = Math.min((time - started) / 1050, 1); setCount(Math.round((1 - Math.pow(1 - progress, 3)) * value)); if (progress < 1) requestAnimationFrame(tick) }; requestAnimationFrame(tick); observer.disconnect() }, { threshold: .7 }); observer.observe(element); return () => observer.disconnect() }, [value]); return <span ref={ref}>{count}{suffix}</span> }

function App() {
  const [menuOpen, setMenuOpen] = useState(false); const [selected, setSelected] = useState(0); const active = solutions[selected]
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const name = data.get('name'); const email = data.get('email'); const message = data.get('message'); window.open(whatsappUrl(`Olá, sou ${name}.\nE-mail: ${email}\n\n${message || 'Gostaria de conversar sobre uma solução da Orkestia.'}`), '_blank', 'noopener,noreferrer') }
  return <>
    <header className="header"><a className="brand" href="#inicio" aria-label="Início"><img src={logo} alt="Orkestia" /></a><button className="menuButton" onClick={() => setMenuOpen(!menuOpen)} aria-label="Abrir menu">{menuOpen ? <X /> : <Menu />}</button><nav className={menuOpen ? 'nav open' : 'nav'}><a onClick={() => setMenuOpen(false)} href="#quem-somos">Quem somos</a><a onClick={() => setMenuOpen(false)} href="#solucoes">Soluções</a><a onClick={() => setMenuOpen(false)} href="#servicos">Serviços</a><a onClick={() => setMenuOpen(false)} href="#contato">Contato</a></nav><a className="button headerCta" target="_blank" rel="noreferrer" href={whatsappUrl('Olá! Gostaria de falar com um especialista da Orkestia.')}>Falar com especialista <ArrowRight size={16}/></a></header>
    <main>
      <section id="inicio" className="hero section-dark"><div className="container split"><Reveal className="heroCopy"><span className="eyebrow">Tecnologia que trabalha ao seu lado</span><h1>Sua empresa em <em>perfeita harmonia.</em></h1><p>Conectamos pessoas, processos e inteligência para impulsionar a evolução digital do seu negócio.</p><a className="button" href="#solucoes">Conheça as soluções <ArrowRight size={16}/></a></Reveal><Reveal className="from-right"><img className="heroImage floating" src={hero} alt="Ecossistema tecnológico Orkestia" /></Reveal></div></section>
      <section id="quem-somos" className="section container story"><Reveal><span className="eyebrow blue">Orkestia · tecnologia que conecta</span><h2>Nossa história<br/>&amp; solidez</h2><p>A Orkestia nasceu do encontro entre experiência, conhecimento e inovação. Criamos soluções que conectam pessoas, processos e resultados para gerar impacto real.</p></Reveal><Reveal className="from-right"><aside><span>GRUPO HTO</span><h3>Uma ponte entre estratégia, tecnologia e operação.</h3><p>Como parte do Grupo HTO, unimos integração de consultoria, engenharia e capacitação profissional em uma estrutura preparada para construir soluções aplicáveis e de alto valor.</p></aside></Reveal></section>
      <section className="metrics"><div className="container metricGrid"><div><strong><Counter value={3}/></strong><span>soluções especializadas</span></div><div><strong><Counter value={1} suffix=" só ecossistema"/></strong><span>para conectar sua operação</span></div><div><strong><Counter value={100} suffix="%"/></strong><span>orientado ao seu negócio</span></div></div></section>
      <section id="solucoes" className="section muted"><div className="container"><Reveal><span className="eyebrow blue">Nossas soluções</span><h2>Um ecossistema para<br/>cada desafio.</h2></Reveal><div className="cards">{solutions.map((item, index) => <Reveal className="cardReveal" key={item.title}><article className={selected === index ? 'card active' : 'card'} onClick={() => setSelected(index)}><img src={item.image} alt=""/><div><span>{item.tag}</span><h3>{item.title}</h3><p>{item.text}</p><button type="button" className="textButton">Explorar solução <ArrowRight size={16}/></button></div></article></Reveal>)}</div><Reveal><div className="solutionPanel"><div><span className="eyebrow blue">Em destaque</span><h3>{active.title}</h3><p>{active.text}</p></div><ul>{active.features.map(feature => <li key={feature}><Check size={17}/>{feature}</li>)}</ul><a className="button" target="_blank" rel="noreferrer" href={whatsappUrl(`Olá! Gostaria de conhecer melhor o ${active.title}.`)}>Quero conhecer <ArrowRight size={16}/></a></div></Reveal></div></section>
      <section id="servicos" className="section-dark services"><div className="container split"><Reveal><span className="eyebrow">Soluções sob medida</span><h2>Desenvolvimento<br/><em>personalizado.</em></h2><p>Sua necessidade, nossa arquitetura. Criamos plataformas e ferramentas pensadas para sua operação — da ideia à solução que realmente funciona.</p><ul><li><Check size={17}/> Sistemas web e aplicativos</li><li><Check size={17}/> Integrações e automações</li><li><Check size={17}/> Dados e inteligência aplicada</li></ul><a className="button" target="_blank" rel="noreferrer" href={whatsappUrl('Olá! Gostaria de conversar sobre desenvolvimento personalizado.')}>Fale conosco <ArrowRight size={16}/></a></Reveal><Reveal className="from-right"><img className="development floating" src={development} alt="Desenvolvimento de soluções personalizadas"/></Reveal></div></section>
      <section id="contato" className="section contact"><Reveal className="container contactBox"><div><span className="eyebrow blue">Vamos conversar</span><h2>Transforme seu desafio em uma solução.</h2><p>Preencha os dados e a conversa será aberta diretamente no WhatsApp da Orkestia.</p></div><form onSubmit={submit}><input name="name" placeholder="Seu nome" required/><input name="email" type="email" placeholder="E-mail corporativo" required/><textarea name="message" placeholder="Como podemos ajudar?" rows={4}/><button className="button" type="submit">Continuar no WhatsApp <MessageCircle size={16}/></button></form></Reveal></section>
    </main>
    <a className="whatsappFloat" target="_blank" rel="noreferrer" href={whatsappUrl('Olá! Gostaria de falar com a Orkestia.')} aria-label="Falar no WhatsApp"><MessageCircle size={23}/></a>
    <footer><div className="container footer"><img src={logo} alt="Orkestia"/><p>© {new Date().getFullYear()} Orkestia Soluções Tecnológicas</p><div><a href="#inicio">Instagram</a><a href="#inicio">LinkedIn</a></div></div></footer>
  </>
}
createRoot(document.getElementById('root')!).render(<App />)
